import { ConnectWallet } from "@thirdweb-dev/react";
import styles from "../styles/Home.module.css";
import Hero from "../components/landinpage/Hero";
import Head from "next/head";

export default function Home() {
  return (
       <><Head>
      <title>MedDocs</title>
      <meta name="description" content="Generated by create next app" />
    
      <link rel="icon" href="/favicon.ico" />
    </Head><Hero />
    </>
    
  );
}
